server:
  port: 9998
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
spring:
  thymeleaf:
    mode: LEGACYHTML5
    #编码 可不用配置
    encoding: UTF-8
    #开发配置为false,避免修改模板还要重启服务器
    cache: false
    #配置模板路径，默认是templates，可以不用配置
    prefix: classpath:/templates/
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 1800000
    password:
    lettuce:
      pool:
        max-active: 20 #最大连接数
        max-wait: -1    #最大阻塞等待时间(负数表示没限制)
        max-idle: 5    #最大空闲
        min-idle: 0     #最小空闲
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:8081/yygh_manage?characterEncoding=utf-8&useSSL=false
    username: root
    password: admin
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 120000 # 连接超时：120秒
      idle-timeout: 600000 # 空闲超时：600秒
      max-lifetime: 1800000 # 最大生命周期：1800秒（30分钟）
      maximum-pool-size: 20 # 最大连接池大小：20
      minimum-idle: 10 # 最小空闲连接数：10
      pool-name: GuliHikariPool
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
